### ISSUE TITLE
Problems for all examples

### ISSUE THREAD

**Issue by ManPython** [vlang/ui#195] opened 2020-08-14 16:46 UTC
**V and UI versions:** v-0.1.29
**OS:** W7

**What did you do?**
```
v run E:\v-0.1.29\v\examples\examples_ui\resizable_window.v
vlib\ui\button.v:16:12: error: undefined ident: `gg.default_font_size`
   14 |         // color: gx.white
   15 |         color: gx.rgb(38, 38, 38)
   16 |         size: gg.default_font_size
      |                  ~~~~~~~~~~~~~~~~~
   17 |         align: gx.align_left
   18 |     }
vlib\ui\button.v:55:2: error: unknown type `gg.Image`
   53 |     text       string
   54 |     icon_path  string
   55 |     image      gg.Image
      |     ~~~~~~~~~~~~~~~~~~~
   56 |     use_icon   bool
   57 | }
vlib\ui\button.v:64:21: error: unknown method: `gg.Context.create_image`
   62 |     b.ui = ui
   63 |     if b.use_icon {
   64 |         b.image = b.ui.gg.create_image(b.icon_path)
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~
   65 |     }
   66 |     mut subscriber := parent.get_subscriber()
vlib\ui\button.v:122:41: error: unknown method: `gg.Context.text_size`
  120 | fn (mut b Button) draw() {
  121 |     if b.text_width == 0 || b.text_height == 0 {
  122 |         b.text_width, b.text_height = b.ui.gg.text_size(b.text)
      |                                               ~~~~~~~~~~~~~~~~~
  123 |         b.width = b.text_width + button_horizontal_padding
  124 |         b.height = b.text_height + button_vertical_padding
vlib\ui\button.v:139:11: error: cannot use type `gg.Image` as type `u32` in argument 5 to `gg.Context.draw_image`
  137 |     }
  138 |     if b.use_icon {
  139 |         b.ui.gg.draw_image(b.x, b.y, b.width, b.height, b.image)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  140 |     }
  141 |     else {
vlib\ui\button.v:142:11: error: unknown method: `gg.Context.draw_text`
  140 |     }
  141 |     else {
  142 |         b.ui.gg.draw_text(bcenter_x-w2, y, b.text, btn_text_cfg)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  143 |     }
  144 |     //b.ui.gg.draw_empty_rect(bcenter_x-w2, bcenter_y-h2, text_width, text_height, button_border_color)
vlib\ui\checkbox.v:54:22: error: unknown method: `gg.Context.text_width`
   52 |     ui := parent.get_ui()
   53 |     cb.ui = ui
   54 |     cb.width = cb.ui.gg.text_width(cb.text) + 5 + check_mark_size
      |                         ~~~~~~~~~~~~~~~~~~~~
   55 |     mut subscriber := parent.get_subscriber()
   56 |     subscriber.subscribe_method(events.on_click, cb_click, cb)
vlib\ui\checkbox.v:113:11: error: cannot use type `gg.Image` as type `u32` in argument 5 to `gg.Context.draw_image`
  111 |         b.ui.gg.draw_line_c(0.5+x0, y1, -3.5+x0+check_mark_size, y0, gx.black)
  112 |         */
  113 |         b.ui.gg.draw_image(b.x + 3, b.y + 3, 8, 8, b.ui.cb_image)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  114 |     }
  115 |     // Text
vlib\ui\checkbox.v:116:10: error: unknown method: `gg.Context.draw_text`
  114 |     }
  115 |     // Text
  116 |     b.ui.gg.draw_text(b.x + check_mark_size + 5, b.y, b.text, btn_text_cfg)
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  117 | }
  118 |
vlib\ui\dropdown.v:95:6: error: unknown method: `gg.Context.draw_text_def`
   93 |     gg.draw_empty_rect(dd.x, dd.y, dd.width, dropdown_height, border_color)
   94 |     if dd.selected_index >= 0 {
   95 |         gg.draw_text_def(dd.x + 5, dd.y + 5, dd.items[dd.selected_index].text)
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |     } else {
   97 |         gg.draw_text_def(dd.x + 5, dd.y + 5, dd.def_text)
vlib\ui\dropdown.v:97:6: error: unknown method: `gg.Context.draw_text_def`
   95 |         gg.draw_text_def(dd.x + 5, dd.y + 5, dd.items[dd.selected_index].text)
   96 |     } else {
   97 |         gg.draw_text_def(dd.x + 5, dd.y + 5, dd.def_text)
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   98 |     }
   99 |
vlib\ui\dropdown.v:109:7: error: unknown method: `gg.Context.draw_text_def`
  107 |             gg.draw_rect(dd.x, y + i * dropdown_height, dd.width, dropdown_height, color)
  108 |             gg.draw_empty_rect(dd.x, y + i * dropdown_height, dd.width, dropdown_height, border_color)
  109 |             gg.draw_text_def(dd.x + 5, y + i * dropdown_height + 5, item.text)
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  110 |         }
  111 |     }
vlib\ui\group.v:90:63: error: unknown method: `gg.Context.text_width`
   88 |     b.ui.gg.draw_empty_rect(b.x, b.y, b.width, b.height, gx.gray)
   89 |     // Title
   90 |     b.ui.gg.draw_rect(b.x + check_mark_size, b.y - 5, b.ui.gg.text_width(b.title) + 5, 10, default_window_color)
      |                                                               ~~~~~~~~~~~~~~~~~~~~
   91 |     b.ui.gg.draw_text_def(b.x + check_mark_size + 3, b.y - 7, b.title)
   92 |
vlib\ui\group.v:91:13: error: unknown method: `gg.Context.draw_text_def`
   89 |     // Title
   90 |     b.ui.gg.draw_rect(b.x + check_mark_size, b.y - 5, b.ui.gg.text_width(b.title) + 5, 10, default_window_color)
   91 |     b.ui.gg.draw_text_def(b.x + check_mark_size + 3, b.y - 7, b.title)
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   92 |
   93 |     for child in b.children {
vlib\ui\label.v:39:17: error: unknown method: `gg.Context.text_size`
   37 |
   38 | fn (mut b Label) size() (int, int) {
   39 |     w,h := b.ui.gg.text_size(b.text)
      |                    ~~~~~~~~~~~~~~~~~
   40 |
   41 |     // First return the width, then the height multiplied by line count.
vlib\ui\label.v:42:14: error: mismatched types `void` and `int`
   40 |
   41 |     // First return the width, then the height multiplied by line count.
   42 |     return w, h * b.text.split('\n').len
      |                 ^
   43 | }
   44 |
vlib\ui\label.v:46:19: error: unknown method: `gg.Context.text_size`
   44 |
   45 | fn (mut b Label) propose_size(w, h int) (int, int) {
   46 |     ww,hh := b.ui.gg.text_size(b.text)
      |                      ~~~~~~~~~~~~~~~~~
   47 |
   48 |     // First return the width, then the height multiplied by line count.
vlib\ui\label.v:49:16: error: mismatched types `void` and `int`
   47 |
   48 |     // First return the width, then the height multiplied by line count.
   49 |     return ww, hh * b.text.split('\n').len
      |                   ^
   50 | }
   51 |
vlib\ui\label.v:58:11: error: unknown method: `gg.Context.draw_text`
   56 |     for i, split in splits {
   57 |         // Draw the text at b.x and b.y + line height * current line
   58 |         b.ui.gg.draw_text(b.x, b.y + (height * i), split, btn_text_cfg)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   59 |     }
   60 | }
vlib\ui\listbox.v:96:23: error: unknown method: `gg.Context.text_width`
   94 |
   95 | fn (mut lb ListBox) get_draw_to(text string) int {
   96 |     width := lb.ui.gg.text_width(text)
      |                       ~~~~~~~~~~~~~~~~
   97 |     real_w := lb.width - _text_offset_x * 2
   98 |     mut draw_to := text.len
vlib\ui\listbox.v:101:37: error: unknown method: `gg.Context.text_width`
   99 |     if width >= real_w {
  100 |         draw_to = int(f32(text.len) * (f32(real_w) / f32(width)))
  101 |         for draw_to > 1 && lb.ui.gg.text_width(text[0..draw_to]) > real_w {
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  102 |             draw_to--
  103 |         }
vlib\ui\listbox.v:177:14: error: unknown method: `gg.Context.draw_text_def`
  175 |     col := if selected { lb.col_selected } else { lb.col_bkgrnd }
  176 |     lb.ui.gg.draw_rect(li.x, li.y, lb.width, lb.item_height, col)
  177 |     lb.ui.gg.draw_text_def(li.x+_text_offset_x, li.y+lb.text_offset_y, li.draw_text)
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  178 |
  179 |     if lb.draw_lines {
vlib\ui\listbox.v:188:51: error: unknown method: `gg.Context.text_height`
  186 |     lb.ui = parent.get_ui()
  187 |     lb.draw_count = lb.height / lb.item_height
  188 |     lb.text_offset_y = (lb.item_height - lb.ui.gg.text_height('W')) / 2
      |                                                   ~~~~~~~~~~~~~~~~
  189 |     if lb.text_offset_y < 0 {
  190 |         lb.text_offset_y = 0
vlib\ui\menu.v:73:11: error: unknown method: `gg.Context.draw_text_def`
   71 |     gg.draw_empty_rect(m.x, m.y, 150, m.items.len * menu_height, menu_border_color)
   72 |     for i, item in m.items {
   73 |         m.ui.gg.draw_text_def(m.x + 10, m.y + i * menu_height  +10, item.text)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   74 |     }
   75 | }
vlib\ui\picture.v:23:2: error: unknown type `gg.Image`
   21 |     path      string
   22 |     ui        &UI
   23 |     image     gg.Image
      |     ~~~~~~~~~~~~~~~~~~
   24 |     on_click  PictureClickFn
   25 |     use_cache bool
vlib\ui\picture.v:43:25: error: unknown method: `gg.Context.create_image`
   41 |         pic.image = ui.resource_cache[pic.path]
   42 |     } else {
   43 |         pic.image = pic.ui.gg.create_image(pic.path)
      |                               ~~~~~~~~~~~~~~~~~~~~~~
   44 |         ui.resource_cache[pic.path] = pic.image
   45 |     }
vlib\ui\radio.v:52:21: error: unknown method: `gg.Context.text_width`
   50 |         mut max := 0
   51 |         for value in r.values {
   52 |             width := r.ui.gg.text_width(value)
      |                              ~~~~~~~~~~~~~~~~~
   53 |             if width > max {
   54 |                 max = width
vlib\ui\radio.v:102:60: error: unknown method: `gg.Context.text_width`
  100 |     b.ui.gg.draw_empty_rect(b.x, b.y, b.width, b.values.len * (b.height + 5), gx.gray)
  101 |     // Title
  102 |     b.ui.gg.draw_rect(b.x + check_mark_size, b.y - 5, b.ui.gg.text_width(b.title) + 5, 10, default_window_color)
      |                                                               ~~~~~~~~~~~~~~~~~~~~
  103 |     b.ui.gg.draw_text_def(b.x + check_mark_size + 3, b.y - 7, b.title)
  104 |     // Values
vlib\ui\radio.v:103:10: error: unknown method: `gg.Context.draw_text_def`
  101 |     // Title
  102 |     b.ui.gg.draw_rect(b.x + check_mark_size, b.y - 5, b.ui.gg.text_width(b.title) + 5, 10, default_window_color)
  103 |     b.ui.gg.draw_text_def(b.x + check_mark_size + 3, b.y - 7, b.title)
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  104 |     // Values
  105 |     for i, val in b.values {
vlib\ui\radio.v:108:11: error: cannot use type `gg.Image` as type `u32` in argument 5 to `gg.Context.draw_image`
  106 |         y := b.y + b.height * i + 15
  107 |         x := b.x + 5
  108 |         b.ui.gg.draw_image(x, y-1, 16, 16, b.ui.selected_radio_image)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  109 |         if i != b.selected_index {
  110 |             b.ui.gg.draw_rect(x+4,y+3,8,8,gx.white) // hide the black circle
vlib\ui\radio.v:114:11: error: unknown method: `gg.Context.draw_text`
  112 |         }
  113 |         // Text
  114 |         b.ui.gg.draw_text(b.x + check_mark_size + 10, y, val, btn_text_cfg)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  115 |     }
  116 | }
vlib\ui\rectangle.v:98:38: error: mismatched types `void` and `any_int`
   96 |         text_width,text_height := r.ui.gg.text_size(r.text)
   97 |         mut dx := (r.width - text_width) / 2
   98 |         mut dy := (r.height - text_height) / 2
      |                                            ^
   99 |         if dx < 0 {
  100 |             dx = 0
vlib\ui\rectangle.v:100:9: error: cannot assign `any_int` to `dx` of type `void`
   98 |         mut dy := (r.height - text_height) / 2
   99 |         if dx < 0 {
  100 |             dx = 0
      |                  ^
  101 |         }
  102 |         if dy < 0 {
vlib\ui\rectangle.v:105:11: error: unknown method: `gg.Context.draw_text`
  103 |             dy = 0
  104 |         }
  105 |         r.ui.gg.draw_text(r.x + dx, r.y + dy, r.text, text_cfg)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  106 |     }
  107 | }
vlib\ui\textbox.v:20:12: error: undefined ident: `gg.default_font_size`
   18 |     placeholder_cfg = gx.TextCfg{
   19 |         color: gx.gray
   20 |         size: gg.default_font_size
      |                  ~~~~~~~~~~~~~~~~~
   21 |         align: gx.align_left
   22 |     }
vlib\ui\textbox.v:190:49: error: unknown method: `gg.Context.text_width`
  188 |         draw_inner_border(t.border_accentuated, t.ui.gg, t.x, t.y, t.width, t.height, t.is_error != 0 && *t.is_error)
  189 |     }
  190 |     width := if text.len == 0 { 0 } else { t.ui.gg.text_width(text) }
      |                                                    ~~~~~~~~~~~~~~~~~
  191 |     text_y := t.y + 2 // TODO off by 1px
  192 |     mut skip_idx := 0
vlib\ui\textbox.v:195:11: error: unknown method: `gg.Context.draw_text`
  193 |     // Placeholder
  194 |     if text == '' && placeholder != '' {
  195 |         t.ui.gg.draw_text(t.x + textbox_padding, text_y, placeholder, placeholder_cfg)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  196 |     }
  197 |     // Text
vlib\ui\textbox.v:205:33: error: unknown method: `gg.Context.text_width`
  203 |             left := ustr.left(t.sel_start)
  204 |             right := ustr.right(t.sel_end)
  205 |             sel_width := width - t.ui.gg.text_width(right) - t.ui.gg.text_width(left)
      |                                          ~~~~~~~~~~~~~~~~~~
  206 |             x := t.ui.gg.text_width(left) + t.x + textbox_padding
  207 |             t.ui.gg.draw_rect(x, t.y + 3, sel_width, t.height - 6, selection_color)
vlib\ui\textbox.v:206:17: error: unknown method: `gg.Context.text_width`
  204 |             right := ustr.right(t.sel_end)
  205 |             sel_width := width - t.ui.gg.text_width(right) - t.ui.gg.text_width(left)
  206 |             x := t.ui.gg.text_width(left) + t.x + textbox_padding
      |                          ~~~~~~~~~~~~~~~~~
  207 |             t.ui.gg.draw_rect(x, t.y + 3, sel_width, t.height - 6, selection_color)
  208 |             /*
vlib\ui\textbox.v:219:16: error: unknown method: `gg.Context.text_width`
  217 |                     continue
  218 |                 }
  219 |                 if t.ui.gg.text_width(text[i..]) > t.width {
      |                            ~~~~~~~~~~~~~~~~~~~~~~
  220 |                     skip_idx = i + 3
  221 |                     break
vlib\ui\textbox.v:224:12: error: unknown method: `gg.Context.draw_text_def`
  222 |                 }
  223 |             }
  224 |             t.ui.gg.draw_text_def(t.x + textbox_padding, text_y, text[skip_idx..])
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  225 |         }
  226 |         else {
vlib\ui\textbox.v:234:13: error: unknown method: `gg.Context.draw_text_def`
  232 |                 }
  233 |                 */
  234 |                 t.ui.gg.draw_text_def(t.x + textbox_padding, text_y, strings.repeat(`*`, text.len))
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  235 |             }
  236 |             else {
vlib\ui\textbox.v:237:13: error: unknown method: `gg.Context.draw_text_def`
  235 |             }
  236 |             else {
  237 |                 t.ui.gg.draw_text_def(t.x + textbox_padding, text_y, text)
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  238 |             }
  239 |         }
vlib\ui\textbox.v:247:24: error: unknown method: `gg.Context.text_width`
  245 |         mut cursor_x := t.x + textbox_padding
  246 |         if t.is_password {
  247 |             cursor_x += t.ui.gg.text_width(strings.repeat(`*`, t.cursor_pos))
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  248 |         }
  249 |         else if skip_idx > 0 {
vlib\ui\textbox.v:250:24: error: unknown method: `gg.Context.text_width`
  248 |         }
  249 |         else if skip_idx > 0 {
  250 |             cursor_x += t.ui.gg.text_width(text[skip_idx..])
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  251 |         }
  252 |         else if text.len > 0 {
vlib\ui\textbox.v:255:24: error: unknown method: `gg.Context.text_width`
  253 |             // left := t.text[..t.cursor_pos]
  254 |             left := text.ustring().left(t.cursor_pos)
  255 |             cursor_x += t.ui.gg.text_width(left)
      |                                 ~~~~~~~~~~~~~~~~
  256 |         }
  257 |         if text.len == 0 {
vlib\ui\textbox.v:526:21: error: unknown method: `gg.Context.text_width`
  524 |         ustr := t.text.ustring()
  525 |         for i in 1 .. ustr.len {
  526 |             width := t.ui.gg.text_width(ustr.left(i))
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~
  527 |             if prev_width <= x && x <= width {
  528 |                 if i < t.sel_start && t.sel_end < t.sel_start {
vlib\ui\textbox.v:541:17: error: cannot assign `void` to `prev_width` of type `int`
  539 |                 return
  540 |             }
  541 |             prev_width = width
      |                          ~~~~~
  542 |         }
  543 |         if reverse {
vlib\ui\textbox.v:577:20: error: unknown method: `gg.Context.text_width`
  575 |     for i in 1 .. ustr.len {
  576 |         // width := t.ui.gg.text_width(t.text[..i])
  577 |         width := t.ui.gg.text_width(ustr.left(i))
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~
  578 |         if prev_width <= x && x <= width {
  579 |             t.cursor_pos = i
vlib\ui\textbox.v:582:16: error: cannot assign `void` to `prev_width` of type `int`
  580 |             return
  581 |         }
  582 |         prev_width = width
      |                      ~~~~~
  583 |     }
  584 |     t.cursor_pos = t.text.len
vlib\ui\ui.v:30:2: error: unknown type `gg.Image`
   28 |     //just_typed           bool
   29 |     last_type_time          i64
   30 |     cb_image             gg.Image
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   31 |     //circle_image         u32
   32 |     radio_image          gg.Image
vlib\ui\ui.v:32:2: error: unknown type `gg.Image`
   30 |     cb_image             gg.Image
   31 |     //circle_image         u32
   32 |     radio_image          gg.Image
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   33 |     selected_radio_image gg.Image
   34 |     down_arrow           gg.Image
vlib\ui\ui.v:33:2: error: unknown type `gg.Image`
   31 |     //circle_image         u32
   32 |     radio_image          gg.Image
   33 |     selected_radio_image gg.Image
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   34 |     down_arrow           gg.Image
   35 |     clipboard            &clipboard.Clipboard
vlib\ui\ui.v:34:2: error: unknown type `gg.Image`
   32 |     radio_image          gg.Image
   33 |     selected_radio_image gg.Image
   34 |     down_arrow           gg.Image
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   35 |     clipboard            &clipboard.Clipboard
   36 |     redraw_requested     bool
vlib\ui\ui.v:223:19: error: too many arguments in call to `gg.create_image_from_memory` (2 instead of 1)
  221 |
  222 | fn (mut ui UI) load_icos() {
  223 |     ui.cb_image = gg.create_image_from_memory(bytes_check_png,  bytes_check_png_len)
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  224 |     /*
  225 |     $if macos {
vlib\ui\ui.v:231:21: error: too many arguments in call to `gg.create_image_from_memory` (2 instead of 1)
  229 |     }
  230 |     */
  231 |     ui.down_arrow = gg.create_image_from_memory(bytes_arrow_png, bytes_arrow_png_len)
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  232 |     ui.selected_radio_image = gg.create_image_from_memory(bytes_selected_radio_png, bytes_selected_radio_png_len)
  233 | }
vlib\ui\ui.v:232:31: error: too many arguments in call to `gg.create_image_from_memory` (2 instead of 1)
  230 |     */
  231 |     ui.down_arrow = gg.create_image_from_memory(bytes_arrow_png, bytes_arrow_png_len)
  232 |     ui.selected_radio_image = gg.create_image_from_memory(bytes_selected_radio_png, bytes_selected_radio_png_len)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  233 | }
  234 |

\v-0.1.29\v>
```

**What did you expect to see?**
Need some working examples. This type errors have for all.
 
**What did you see instead?**
Errors.

**Comment by serkonda7** [comment] 2020-08-19 13:39
Have you tried `v up` and `v update ui` already?

**Comment by ManPython** [comment] 2020-08-19 15:30
@serkonda7 now on new version window is opened

V version: V 0.1.29 eabc2da
Current V version:
V 0.1.29 eabc2da


but..
```
v run "C:\Users\user\.vmodules\ui\examples\resizable_window.v"
E:\v-0.1.29\v\vlib\clipboard\clipboard_windows.c.v:136:15: warning: pointer indexing is only allowed in `unsafe` blocks
  134 |         mut locked := &u16(C.GlobalLock(buf))
  135 |         C.MultiByteToWideChar(C.CP_UTF8, C.MB_ERR_INVALID_CHARS, text.str, text.len + 1, locked, len_required)
  136 |         locked[len_required - 1] = u16(0)
      |               ~~~~~~~~~~~~~~~~~~
  137 |         C.GlobalUnlock(buf)
  138 |     }
E:\v-0.1.29\v\thirdparty\stb_image\stbi.o not found, building it...

V UI: icon file "" not found
The alternate text will be used.
failed to load font "SFNS-bold.ttf"
failed to load font "/System/Library/Fonts/SFNSMono.ttf"
failed to load font "/System/Library/Fonts/SFNSItalic.ttf"
```

Also I made many other test around V and testing all.
https://github.com/vlang/v/issues/6133

**Comment by serkonda7** [comment] 2020-08-19 15:38
This warning can easily be fixed. You could submit a PR on your own.

**Comment by ManPython** [comment] 2020-08-19 15:55
Some questions 
1. about resize - the background is refreshed after mouse button is relased as out. In this exist some "grapchic artifact" when scaling etc. Can we solve this? As refresing in press stage or something?
a) I am on Windows
b) Is this articfact this same on Linux? 
- asking due other examples with opengl, etc. "visual libs" as on links, where other type artifact exist
![v resize_window](https://user-images.githubusercontent.com/25403861/90659373-e40e0900-e244-11ea-9e3c-b2979feddd7d.png)


2. the cmd window with the log - can be easy turned off as default? (I am "new" with V)

**Comment by serkonda7** [comment] 2020-08-19 16:03
1. On Linux there are no persistent artifacts. The app is redrawn nearly in realtime. (I cannot tell for windows, sorry)
2. If you use `v run ...`, you can't. But you are able to execute the exe file after build, which won't show the terminal.

**Comment by ManPython** [comment] 2020-08-19 16:06
@serkonda7 
1. I am on Win so.. exist this type - was curious how on LNX
2. I runing resizable_window.exe after v run builded this exe but cmd window is opened.

**Comment by serkonda7** [comment] 2020-08-19 16:07
You should see the .exe file in the examples directory, just double-click on it.

**Comment by ManPython** [comment] 2020-08-19 16:11
I'am doing this and with the exe is clicked then runed cmd C:\Users\user\.vmodules\ui\examples\resizable_window.exe as on your images. Soo.. maybe again some issue around WIN not LNX?

**Comment by serkonda7** [comment] 2020-08-19 16:20
So I just started my old and hated windows PC.
1. I can confirm the artifacts (I will create a new issue for this)
2. To run without the terminal do the following:
  1. Run `v resizable_window.v` in cmd (only needed for this step)
  2. Close cmd
  3. Navigate to the examples folder in your file explorer
  4. Look for `resizable_window.exe`
  5. Double-click on it

**Comment by ManPython** [comment] 2020-08-19 16:26
Regarding the cms.. maybe this happen due that I not have the .tff and the logs must be printed somewhere?
HVR should exist option to omit cmd/logs or put this to .txt maybe.

Note that, about articfacts, that exist on opengl and other type visual graphic libs what I tested.

**Comment by serkonda7** [comment] 2020-08-20 07:11
> but..
I proposed a PR that will fix this warning: https://github.com/vlang/v/pull/6178
Furthermore I proposed a PR for the CI to catch such things earlier: https://github.com/vlang/ui/pull/204

Regarding the cmd: Maybe it happens because you you Win7 and I have Win10...

The option to output logs to a file is an nice idea. Could you create a feature request please?

**Comment by serkonda7** [comment] 2020-08-20 10:06
I will close this now, because the remaining problems have got their own issues.

**Closed by serkonda7** 2020-08-20 10:06 UTC
Labels: bug
