### ISSUE TITLE
The examples are compiled, but not run.

### ISSUE THREAD

**Issue by Keyn1** [vlang/ui#484] opened 2022-10-10 16:55 UTC
**V version:* 0.3.1*
**UI version:* last*
**OS:*windows 10* 

**What did you do?**
The examples are compiled, but not run.

**What did you expect to see?**
File: C:/V/v-master/thirdparty/sokol/sokol_gfx.h
Line: 15461
Expression: _sg.valid
 
**What did you see instead?**

**Comment by tehando** [comment] 2022-10-19 13:56
All "ui" examples give the same output for Arch based Linux/GNU
platform = Linux-6.0.2-arch1-1-x86_64-with-glibc2.36

...examples]$ ./slider
V panic: toml.checker.Checker.check_number numbers like "0." (float) can not end with `.` in ...radius = 0.\nbg_color...
v hash: d781396
/tmp/v_1000/slider.7555115272680828670.tmp.c:23643: at _v_panic: Backtrace
/tmp/v_1000/slider.7555115272680828670.tmp.c:60629: by ui__parse_style_toml_file
/tmp/v_1000/slider.7555115272680828670.tmp.c:60681: by ui__UI_load_style_from_file
/tmp/v_1000/slider.7555115272680828670.tmp.c:60676: by ui__UI_load_styles
/tmp/v_1000/slider.7555115272680828670.tmp.c:58063: by ui__window
/tmp/v_1000/slider.7555115272680828670.tmp.c:2464: by main__main
/tmp/v_1000/slider.7555115272680828670.tmp.c:3386: by main

**Comment by Bellisario** [comment] 2022-10-19 14:00
Same problem for me

**Comment by igrekus** [comment] 2022-10-29 23:24
Reproduces on Ubuntu 20.04 also.

**Comment by frpaulas** [comment] 2022-10-31 19:50
same on pop 22.04

**Comment by vaaski** [comment] 2022-11-05 19:49
Same on macOS Monterey

**Comment by spytheman** [comment] 2022-11-07 07:47
I could not reproduce the problem with latest V and latest ui.

Please anyone who can reproduce it, try if the following fixes it:
```sh
mv ~/.vmodules/ui ~/.vmodules/old_ui
v up
v install ui
v run ~/.vmodules/ui/examples/slider.v
```

**Comment by spytheman** [comment] 2022-11-07 07:58
I found the problem - I had a preexisting `~/.vui/styles/` folder containing valid .toml files.
Latest V or UI, not sure yet, produces invalid .toml files, if they are missing.

**Comment by spytheman** [comment] 2022-11-07 08:07
A preliminary fix (just ignoring the invalid .toml files is in latest ui 95d98d8).

**Comment by frpaulas** [comment] 2022-11-07 14:04
looks good, 10Q

**Comment by tehando** [comment] 2022-11-07 20:43
Examples are ok, you can close this issue. [https://images2.imgbox.com/34/e3/ctbcbAj8_o.png](url)

**Comment by Keyn1** [comment] 2022-11-09 08:06
Downloaded the latest versions.
work: demo_canvaslayout.exe , demo_radio.exe ,  slider.exe , grid.exe

error: 
       change_title.exe , child_window.exe , group2_resizable.exe , users.exe

C:\Users\Keyn\.vmodules\ui\examples>Unhandled Exception 0xC0000005                                                                         ↑
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:23692: at print_backtrace_skipping_top_frames_tcc: Backtraceны
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:23659: by print_backtrace_skipping_top_frames
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:23717: by unhandled_exception_handler
7ffe7f088b9c : by ???
7ffe7d6943d7 : at ???: RUNTIME ERROR: invalid memory access
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:54969: by ui__Stack_draw_device
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:54969: by ui__Stack_draw_device
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:54942: by ui__Stack_draw
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:55596: by ui__frame
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:40819: by gg__gg_frame_fn
C:/V/v-master/thirdparty/sokol/sokol_app.h:2630: by _sapp_call_frame
C:/V/v-master/thirdparty/sokol/sokol_app.h:2833: by _sapp_frame
C:/V/v-master/thirdparty/sokol/sokol_app.h:7198: by _sapp_win32_run
C:/V/v-master/thirdparty/sokol/sokol_app.h:11234: by sapp_run
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:39393: by sokol__sapp__run
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:41053: by gg__Context_run
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:59253: by ui__run
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:65372: by main__main
C:/Users/Keyn/AppData/Local/Temp/v_0/users.1061303563581735944.tmp.c:789: by wWinMain
006ea08f : by ???
006ea1f0 : by ???
7ffe7d347034 : by ???

**Closed** 2022-11-12 09:25 UTC
Labels: bug
